#-------------------------
# host_vars/node1
#-------------------------
# ntp server
ntp:
  is_server: true
  is_client: false

common_fs:
  size: 1024
  file: "/var/tmp/ansible_test_common.img"
  mount_point: /mnt/ansible_test_common

unique_fs:
  size: 1024
  file: "/var/tmp/ansible_test_{{ inventory_hostname }}.img"
  mount_point: /mnt/ansible_test_{{ inventory_hostname }}