all: 
  children: 
    ntp_server:
      hosts:
        node1: 
          ansible_host: 127.0.0.1
          ansible_port: 2223
          ansible_user: ans
          ansible_connection: ssh
          ansible_ssh_private_key_file: /home/User/.ssh/id_ed25519 # SSH接続用の秘密鍵
          ansible_python_interpreter: /usr/bin/python3 # python3を使用
    ntp_client:
      hosts:
        node2:
          ansible_host: 127.0.0.1
          ansible_port: 2224
          ansible_user: ans
          ansible_connection: ssh
          ansible_ssh_private_key_file: /home/User/.ssh/id_ed25519
          ansible_python_interpreter: /usr/bin/python3