name: "infra dev preview & deploy"

on:
  push:
    branches:
      - main
    paths:
      - infra/environment/**
      - .github/workflows/**
  workflow_dispatch:

env:
  TF_VERSION: 1.13.4
  TF_PROJECT: ansible
  TF_VARFILE: terraform.tfvars.dev-exam
  TF_ENVIRONMENT: dev
  AWS_REGION: ap-northeast-1

defaults:
  run:
    shell: bash
    working-directory: "infra/environment/dev/"

# Githubからﾄｰｸﾝ、ｺｰﾄﾞを取得する権限
permissions:
  id-token: write
  contents: read

jobs:
  preview:
    name: "preview"
    runs-on: ubuntu-latest
    steps:
      # --- Setup Phase ---
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
      
      - name: Configure AWS Cred
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
        # GithubのシークレットにIAMロールのARNを登録しておく
        # Github → repo → settings → Secrets and vars → Actions → New repo secret

      # --- Validate Phase ---
      - name: Terraform Init
        run: | 
          terraform init -no-color
        # -no-color: ｶﾗｰｺｰﾄﾞを無効化(ﾛｸﾞ出力用)

      - name: Terraform Format
        run: | 
          terraform fmt -check
        # -check: ﾌｫｰﾏｯﾄが正ならば0を返す
      
      - name: Terraform Validate
        run: | 
          terraform validate -no-color
      
      # --- Plan Phase ---
      - name: Terraform Plan
        run: | 
          terraform plan \
            -var-file=${{ env.TF_VARFILE }} \
            -var 'project=${{ env.TF_PROJECT }}' \
            -var 'env=${{ env.TF_ENVIRONMENT }}' \
            -input=false \
            -no-color \
            -detailed-exitcode
        # -input-false: 値が未割当の変数があっても処理を継続
        # -detailed-exitcode: planの詳細情報を返す
        # (0:差分なし, 1:エラー, 2: 差分あり)...2の場合のみCDへ処理連携が必須
        # DBへの接続ｸﾚﾃﾞﾝｼｬﾙがあれば secretとしてここで渡す

      